# Generated by Django 6.0.2 on 2026-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
